import Complex from './complex';
declare type complex = [number, number];
interface Icast {
    (a: Complex | complex | number | string): Complex;
    add(a: Complex | complex | number | string, ...b: (Complex | complex | number | string)[]): Complex;
    subtract(a: Complex | complex | number | string, ...b: (Complex | complex | number | string)[]): Complex;
    multiply(a: Complex | complex | number | string, ...b: (Complex | complex | number | string)[]): Complex;
    divide(a: Complex | complex | number | string, b: Complex | complex | number | string): Complex;
    power(a: Complex | complex | number | string, b: Complex | complex | number | string): Complex;
    root(a: Complex | complex | number | string, b: number): Complex;
    ln(a: Complex | complex | number | string): Complex;
    log(a: Complex | complex | number | string, b: Complex | complex | number | string): Complex;
    sin(a: Complex | complex | number | string): Complex;
    cos(a: Complex | complex | number | string): Complex;
    tan(a: Complex | complex | number | string): Complex;
    cot(a: Complex | complex | number | string): Complex;
    sec(a: Complex | complex | number | string): Complex;
    csc(a: Complex | complex | number | string): Complex;
    asin(a: Complex | complex | number | string): Complex;
    acos(a: Complex | complex | number | string): Complex;
    atan(a: Complex | complex | number | string): Complex;
    acot(a: Complex | complex | number | string): Complex;
    asec(a: Complex | complex | number | string): Complex;
    acsc(a: Complex | complex | number | string): Complex;
    sinh(a: Complex | complex | number | string): Complex;
    cosh(a: Complex | complex | number | string): Complex;
    tanh(a: Complex | complex | number | string): Complex;
    coth(a: Complex | complex | number | string): Complex;
    sech(a: Complex | complex | number | string): Complex;
    csch(a: Complex | complex | number | string): Complex;
    asinh(a: Complex | complex | number | string): Complex;
    acosh(a: Complex | complex | number | string): Complex;
    atanh(a: Complex | complex | number | string): Complex;
    acoth(a: Complex | complex | number | string): Complex;
    asech(a: Complex | complex | number | string): Complex;
    acsch(a: Complex | complex | number | string): Complex;
    abs(a: Complex | complex | number | string): number;
    conjugate(a: Complex | complex | number | string): Complex;
    R(a: Complex | complex | number | string): number;
    I(a: Complex | complex | number | string): number;
    get(a: Complex | complex | number | string): complex;
    stringify(a: Complex | complex | number | string): string;
    evaluate(a: string): string;
    LOGIE: complex;
    LOGEI: complex;
}
declare const cast: Icast;
export default cast;
