"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const complex_1 = require("./complex");
const cast = (a) => (a instanceof complex_1.default) ? a : new complex_1.default(a);
cast.add = (a, ...b) => cast(a).add(...b);
cast.subtract = (a, ...b) => cast(a).subtract(...b);
cast.multiply = (a, ...b) => cast(a).multiply(...b);
cast.divide = (a, b) => cast(a).divide(b);
cast.power = (a, b) => cast(a).power(b);
cast.root = (a, b) => cast(a).root(b);
cast.ln = (a) => cast(a).ln();
cast.log = (a, b) => cast(a).log(b);
cast.sin = (a) => cast(a).sin();
cast.cos = (a) => cast(a).cos();
cast.tan = (a) => cast(a).tan();
cast.cot = (a) => cast(a).cot();
cast.sec = (a) => cast(a).sec();
cast.csc = (a) => cast(a).csc();
cast.asin = (a) => cast(a).asin();
cast.acos = (a) => cast(a).acos();
cast.atan = (a) => cast(a).atan();
cast.acot = (a) => cast(a).acot();
cast.asec = (a) => cast(a).asec();
cast.acsc = (a) => cast(a).acsc();
cast.sinh = (a) => cast(a).sinh();
cast.cosh = (a) => cast(a).cosh();
cast.tanh = (a) => cast(a).tanh();
cast.coth = (a) => cast(a).coth();
cast.sech = (a) => cast(a).sech();
cast.csch = (a) => cast(a).csch();
cast.asinh = (a) => cast(a).asinh();
cast.acosh = (a) => cast(a).acosh();
cast.atanh = (a) => cast(a).atanh();
cast.acoth = (a) => cast(a).acoth();
cast.asech = (a) => cast(a).asech();
cast.acsch = (a) => cast(a).acsch();
cast.abs = (a) => cast(a).abs();
cast.conjugate = (a) => cast(a).conjugate();
cast.R = (a) => cast(a).R();
cast.I = (a) => cast(a).I();
cast.get = (a) => cast(a).get();
cast.stringify = (a) => cast(a).stringify();
cast.evaluate = (a) => cast(a).stringify();
cast.LOGEI = [0, Math.PI / 2];
cast.LOGIE = [0, -2 / Math.PI];
exports.default = cast;
//# sourceMappingURL=cast.js.map