declare type extract<T> = T;
declare type complex = [number, number];
declare type T = extract<Complex | complex | number | string>;
declare class Complex {
    private readonly numbers;
    constructor(a: T);
    stringify(): string;
    add(...a: T[]): Complex;
    subtract(...a: T[]): Complex;
    multiply(...a: T[]): Complex;
    divide(a: T): Complex;
    power(a: T): Complex;
    root(a?: T): Complex;
    ln(): Complex;
    log(a?: T): Complex;
    sin(): Complex;
    cos(): Complex;
    tan(): Complex;
    cot(): Complex;
    sec(): Complex;
    csc(): Complex;
    asin(): Complex;
    acos(): Complex;
    atan(): Complex;
    acot(): Complex;
    asec(): Complex;
    acsc(): Complex;
    sinh(): Complex;
    cosh(): Complex;
    tanh(): Complex;
    coth(): Complex;
    sech(): Complex;
    csch(): Complex;
    asinh(): Complex;
    acosh(): Complex;
    atanh(): Complex;
    acoth(): Complex;
    asech(): Complex;
    acsch(): Complex;
    abs(): number;
    conjugate(): Complex;
    R(): number;
    I(): number;
    get(): complex;
    equal(n: T): boolean;
}
export default Complex;
