declare type complex = [number, number];
declare class Complex {
    private readonly numbers;
    constructor(a: complex | string);
    stringify(): string;
    add(...a: (complex | Complex)[]): Complex;
    subtract(...a: (complex | Complex)[]): Complex;
    multiply(...a: (complex | Complex)[]): Complex;
    divide(a: complex | Complex): Complex;
    power(a: complex | Complex): Complex;
    root(a?: number | Complex): Complex;
    ln(): Complex;
    log(a?: number | complex | Complex): Complex;
    sin(): Complex;
    cos(): Complex;
    tan(): Complex;
    cot(): Complex;
    sec(): Complex;
    csc(): Complex;
    asin(): Complex;
    acos(): Complex;
    atan(): Complex;
    acot(): Complex;
    asec(): Complex;
    acsc(): Complex;
    sinh(): Complex;
    cosh(): Complex;
    tanh(): Complex;
    coth(): Complex;
    sech(): Complex;
    csch(): Complex;
    asinh(): Complex;
    acosh(): Complex;
    atanh(): Complex;
    acoth(): Complex;
    asech(): Complex;
    acsch(): Complex;
    abs(): number;
    conjugate(): Complex;
    R(): number;
    I(): number;
    get(): complex;
}
export default Complex;
